### Check root endpoint
GET {{dictionary-server-host}}/

### Get user words
GET {{dictionary-server-host}}/api/users/106465616438964035743/words
Authorization: Bearer {{auth_token}}

### Add user word
POST {{dictionary-server-host}}/api/users/106465616438964035743/words
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "wordText": "test",
  "translation": "тест"
}
