# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Increment version

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.java'
      - '**.css'
      - '**.html'
      - '**.yml'
      - '**.yaml'
      - '**.json'
      - '**/pom.xml'
      - '**.properties'
      - '**Dockerfile'

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: get next version
        id: 'bump'
        uses: allegro-actions/next-version@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: |
          cd dictionary-server
          ./gradlew currentVersion
